server:
  port: 8469
logging:
  file: /java/C2S_LOGS/iexhub-xdsb/iexhub-xdsb.log
info:
  component: IExHub XDS.b Spring Boot
ribbon:
  ReadTimeout: 50000
hystrix.command.default.execution.timeout.enabled: false
c2s:
  iexhub-xdsb:
    xdsb:
      enabled: true
      # Configure XDS.b Server specific information
      xdsbRegistryEndpointURI: http://bhitsdevhie01:9080/axis2/services/xdsregistryb
      xdsbRepositoryEndpointURI: http://bhitsdevhie01:9080/axis2/services/xdsrepositoryb
      xdsbRepositoryUniqueId: 1.3.6.1.4.1.21367.2010.1.2.1040
      #Also known as Global Domain Id
      homeCommunityId: 2.16.840.1.113883.4.357
      # If getPatientHealthDataBasedOnEnterpriseId=false, call to xds.b registry is made using the local(C2S) MRN
      # If getPatientHealthDataBasedOnEnterpriseId=true, call to xds.b registry is made using the patient's Enterprise ID
      getHealthDataBasedOnEnterpriseId: true
      clientSocketTimeoutInMs: 768000
---
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl-default
server:
  context-path: /iexhub-xdsb